/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Erc20 } from "./Erc20";
export type { Multicall2 } from "./Multicall2";
export type { Weth } from "./Weth";
